from constants import *


def generate_control_map():
    return {
        CTRL_R_TRIGGER: {CTRL_FLAG: False, CTRL_JOYSTICK_FIELD: INPUT_RIGHT_TRIGGER, CTRL_NETWORK_LABEL: NWK_R_TRIGGER},
        CTRL_L_TRIGGER: {CTRL_FLAG: False, CTRL_JOYSTICK_FIELD: INPUT_LEFT_TRIGGER, CTRL_NETWORK_LABEL: NWK_L_TRIGGER},
        CTRL_L_THUMB_Y: {CTRL_FLAG: False, CTRL_JOYSTICK_FIELD: INPUT_LEFT_THUMB_Y, CTRL_NETWORK_LABEL: NWK_L_THUMB_Y},
        CTRL_L_THUMB_X: {CTRL_FLAG: False, CTRL_JOYSTICK_FIELD: INPUT_LEFT_THUMB_X, CTRL_NETWORK_LABEL: NWK_L_THUMB_X},
        CTRL_R_THUMB_Y: {CTRL_FLAG: False, CTRL_JOYSTICK_FIELD: INPUT_RIGHT_THUMB_Y, CTRL_NETWORK_LABEL: NWK_L_THUMB_Y},
        CTRL_R_THUMB_X: {CTRL_FLAG: False, CTRL_JOYSTICK_FIELD: INPUT_RIGHT_THUMB_X, CTRL_NETWORK_LABEL: NWK_L_THUMB_X},

        CTRL_BUTTON_DPAD_UP: {CTRL_FLAG: False, CTRL_JOYSTICK_FIELD: 1, CTRL_NETWORK_LABEL: NWK_DPAD_UP},
        CTRL_BUTTON_DPAD_DOWN: {CTRL_FLAG: False, CTRL_JOYSTICK_FIELD: 2, CTRL_NETWORK_LABEL: NWK_DPAD_DOWN},
        CTRL_BUTTON_DPAD_LEFT: {CTRL_FLAG: False, CTRL_JOYSTICK_FIELD: 3, CTRL_NETWORK_LABEL: NWK_DPAD_LEFT},
        CTRL_BUTTON_DPAD_RIGHT: {CTRL_FLAG: False, CTRL_JOYSTICK_FIELD: 4, CTRL_NETWORK_LABEL: NWK_DPAD_RIGHT},

        CTRL_BUTTON_A: {CTRL_FLAG: False, CTRL_JOYSTICK_FIELD: 13, CTRL_NETWORK_LABEL: NWK_BUTTON_A},
        CTRL_BUTTON_B: {CTRL_FLAG: False, CTRL_JOYSTICK_FIELD: 14, CTRL_NETWORK_LABEL: NWK_BUTTON_B},
        CTRL_BUTTON_X: {CTRL_FLAG: False, CTRL_JOYSTICK_FIELD: 15, CTRL_NETWORK_LABEL: NWK_BUTTON_X},
        CTRL_BUTTON_Y: {CTRL_FLAG: False, CTRL_JOYSTICK_FIELD: 16, CTRL_NETWORK_LABEL: NWK_BUTTON_Y},

        CTRL_BUTTON_L1: {CTRL_FLAG: False, CTRL_JOYSTICK_FIELD: 9, CTRL_NETWORK_LABEL: NWK_BUTTON_L1},
        CTRL_BUTTON_R1: {CTRL_FLAG: False, CTRL_JOYSTICK_FIELD: 10, CTRL_NETWORK_LABEL: NWK_BUTTON_R1},
        CTRL_BUTTON_L3: {CTRL_FLAG: False, CTRL_JOYSTICK_FIELD: 7, CTRL_NETWORK_LABEL: NWK_BUTTON_L3},
        CTRL_BUTTON_R3: {CTRL_FLAG: False, CTRL_JOYSTICK_FIELD: 8, CTRL_NETWORK_LABEL: NWK_BUTTON_R3},

        CTRL_BUTTON_START: {CTRL_FLAG: False, CTRL_JOYSTICK_FIELD: 5, CTRL_NETWORK_LABEL: NWK_BUTTON_START},
        CTRL_BUTTON_BACK: {CTRL_FLAG: False, CTRL_JOYSTICK_FIELD: 6, CTRL_NETWORK_LABEL: NWK_BUTTON_BACK}
    }